### ISSUE TITLE
Compiler warning - iOS 6.0+

### ISSUE THREAD

**Issue by macrolith** [davedelong/DDUnitConverter#3]
In the iOS6 compiler one gets a warning on the line:

dispatch_queue_t currentQueue = dispatch_get_current_queue();

As seen here:

![Screen Shot 2012-12-09 at 5.24.36 PM.png](https://f.cloud.github.com/assets/2514381/2704/45fe91aa-424f-11e2-9a59-73736d4d132e.png)

**Comment by davedelong** [comment]
This has been fixed.
