### ISSUE TITLE
Temperature Unit Converter

### ISSUE THREAD

**Issue by mrushizha** [davedelong/DDUnitConverter#7]
The Réaumur formulae are switched.  Correct as follows:

DDTemperatureUnitConverter.m

switch (from)  {
	.
	.
	.
	case DDTemperatureUnitReaumur:
			numberInCelcius = [numberInCelcius decimalNumberByDividingBy:[NSDecimalNumber decimalNumberWithMantissa:8 exponent:-1 isNegative:NO]];
			break;
	.
	.
	.
}

switch (to) {
	.
	.
	.
	case DDTemperatureUnitReaumur:
			numberInTarget = [numberInTarget decimalNumberByMultiplyingBy:[NSDecimalNumber decimalNumberWithMantissa:8 exponent:-1 isNegative:NO]];
			break;
	.
	.
	.
}

**Comment by davedelong** [comment]
Thanks! :)
